### ISSUE TITLE
crash mod(Fabric server)

### ISSUE THREAD

**Issue by Miros77** [Miros77/Realistic-Bakery-Products---Fabric#11]
[07:43:54] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'realistic_bakery_products'!
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.13.3.jar:?]
at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.13.3.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.13.3.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.13.3.jar:?]
at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.13.3.jar:?]
at net.minecraft.server.Main.main(Main.java:92) [server-intermediary.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.3.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.3.jar:?]
Caused by: java.lang.ExceptionInInitializerError
at rbp.RBP.onInitialize(RBP.java:12) ~[realistic-bakery-products-1.2.9.1.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
... 15 more
Caused by: java.lang.ClassCastException: class rbp.registry.item.RollingPinItem cannot be cast to class rbp.ItemExtension (rbp.registry.item.RollingPinItem and rbp.ItemExtension are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @3ac3fd8b)
at rbp.registry.item.RollingPinItem.<init>(RollingPinItem.java:11) ~[realistic-bakery-products-1.2.9.1.jar:?]
at rbp.registry.ModRegistry.<clinit>(ModRegistry.java:399) ~[realistic-bakery-products-1.2.9.1.jar:?]
at rbp.RBP.onInitialize(RBP.java:12) ~[realistic-bakery-products-1.2.9.1.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
... 15 more

**Comment by Miros77** [comment]
fixed in 1.3.0 [Realistic Bakery Products 1.3.0 [Fabric] 1.16.x](https://www.curseforge.com/minecraft/mc-mods/realistic-bakery-products-fabric/files/3758477)
