### ISSUE TITLE
Multiple Errors at server start

### ISSUE THREAD

**Issue by X00LA** [Miros77/Realistic-Bakery-Products---Fabric#6]
Hi,

I have multiple errors at server start regarding some item tags and recipes:

`[06:52:24] [Worker-Main-13/ERROR]: Couldn't load item tag sandwichable:breads as it is missing following references: sandwichable:toasted_bread_slice (from Realistic Bakery Products),sandwichable:bread_slice (from Realistic Bakery Products)
[06:52:24] [Worker-Main-13/ERROR]: Couldn't load item tag sandwichable:metal_items as it is missing following references: sandwichable:kitchen_knife (from Realistic Bakery Products),sandwichable:toaster (from Realistic Bakery Products),sandwichable:fermenting_milk_bucket (from Realistic Bakery Products)
[06:52:24] [Worker-Main-13/ERROR]: Parsing error loading recipe mechanicaltech:gold_grit_from_common
com.google.gson.JsonSyntaxException: Unknown item tag 'c:gold_ores'
	at net.minecraft.class_1856.method_8107(class_1856.java:171) ~[intermediary-server.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:147) ~[intermediary-server.jar:?]
	at io.engi.mechanicaltech.recipe.ProcessingRecipeSerializer.read(ProcessingRecipeSerializer.java:24) ~[mechanicaltech-0.2.0+1.16.4.jar:?]
	at io.engi.mechanicaltech.recipe.ProcessingRecipeSerializer.method_8121(ProcessingRecipeSerializer.java:12) ~[mechanicaltech-0.2.0+1.16.4.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_272]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_272]
[06:52:24] [Worker-Main-13/ERROR]: Parsing error loading recipe mechanicaltech:mill_from_generic
com.google.gson.JsonSyntaxException: Unknown item tag 'c:wood_gears'
	at net.minecraft.class_1856.method_8107(class_1856.java:171) ~[intermediary-server.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:147) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869.method_8157(class_1869.java:225) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869.method_8159(class_1869.java:24) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:246) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:241) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_272]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_272]
[06:52:24] [Worker-Main-13/ERROR]: Parsing error loading recipe mechanicaltech:iron_grit_from_common
com.google.gson.JsonSyntaxException: Unknown item tag 'c:iron_ores'
	at net.minecraft.class_1856.method_8107(class_1856.java:171) ~[intermediary-server.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:147) ~[intermediary-server.jar:?]
	at io.engi.mechanicaltech.recipe.ProcessingRecipeSerializer.read(ProcessingRecipeSerializer.java:24) ~[mechanicaltech-0.2.0+1.16.4.jar:?]
	at io.engi.mechanicaltech.recipe.ProcessingRecipeSerializer.method_8121(ProcessingRecipeSerializer.java:12) ~[mechanicaltech-0.2.0+1.16.4.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_272]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_272]
[06:52:24] [Worker-Main-13/ERROR]: Parsing error loading recipe mechanicaltech:sawmill_from_generic
com.google.gson.JsonSyntaxException: Unknown item tag 'c:wood_gears'
	at net.minecraft.class_1856.method_8107(class_1856.java:171) ~[intermediary-server.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:147) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869.method_8157(class_1869.java:225) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869.method_8159(class_1869.java:24) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:246) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:241) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_272]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_272]
[06:52:24] [Worker-Main-13/ERROR]: Parsing error loading recipe mechanicaltech:grinder_common
com.google.gson.JsonSyntaxException: Unknown item 'c:wood_gears'
	at net.minecraft.class_1856.method_17873(class_1856.java:165) ~[intermediary-server.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_272]
	at net.minecraft.class_1856.method_8107(class_1856.java:165) ~[intermediary-server.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:147) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869.method_8157(class_1869.java:225) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869.method_8159(class_1869.java:24) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:246) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:241) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_272]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_272]
[06:52:24] [Worker-Main-13/ERROR]: Parsing error loading recipe mechanicaltech:windsail_from_generic
com.google.gson.JsonSyntaxException: Unknown item tag 'c:wood_gears'
	at net.minecraft.class_1856.method_8107(class_1856.java:171) ~[intermediary-server.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:147) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869.method_8157(class_1869.java:225) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869.method_8159(class_1869.java:24) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:246) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:241) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_272]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_272]
[06:52:24] [Worker-Main-13/ERROR]: Parsing error loading recipe mechanicaltech:spindle_from_generic
com.google.gson.JsonSyntaxException: Unknown item tag 'c:wood_gears'
	at net.minecraft.class_1856.method_8107(class_1856.java:171) ~[intermediary-server.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:147) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869.method_8157(class_1869.java:225) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869.method_8159(class_1869.java:24) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:246) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:241) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_272]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_272]
[06:52:24] [Worker-Main-13/ERROR]: Parsing error loading recipe mechanicaltech:waterwheel_from_generic
com.google.gson.JsonSyntaxException: Unknown item tag 'c:wood_gears'
	at net.minecraft.class_1856.method_8107(class_1856.java:171) ~[intermediary-server.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:147) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869.method_8157(class_1869.java:225) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869.method_8159(class_1869.java:24) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:246) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:241) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_272]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) [?:1.8.0_272]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_272]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_272]`

I tested with and without other mods but it's always the same result.

Would be nice if you could fix this.

Regards

**Comment by Miros77** [comment]
Hi these are mod errors (Sandwichable and Mechanicaltech).

**Comment by Miros77** [comment]
In my mod, Mechanicaltech has built-in

**Comment by Miros77** [comment]
I will send this problem to the developer of the Mechanical Tech mod

**Comment by Miros77** [comment]
you need to install the Sandwichable and Cotton resource. Errors will disappear

**Comment by Miros77** [comment]
https://github.com/EngiN33R/MechanicalTech/issues/25

**Comment by Miros77** [comment]
with the release of 1.3.0, this mod will be removed

**Comment by Miros77** [comment]
fixed in 1.3.0 [Realistic Bakery Products 1.3.0 [Fabric] 1.16.x](https://www.curseforge.com/minecraft/mc-mods/realistic-bakery-products-fabric/files/3758477)
