### ISSUE TITLE
Error of missing mechanical_tech dependencies in 1.2.0 of realistic bakery

### ISSUE THREAD

**Issue by x-sis** [Miros77/Realistic-Bakery-Products---Fabric#8]
Hello,

after installing of this mod I have an error on my fabric server:

[19:07:14] [Worker-Main-14/ERROR]: Parsing error loading recipe mechanicaltech:mill_from_generic
com.google.gson.JsonSyntaxException: Unknown item tag 'c:wood_gears'
        at net.minecraft.class_1856.method_8107(class_1856.java:171) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1856.method_8102(class_1856.java:147) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869.method_8157(class_1869.java:225) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869.method_8159(class_1869.java:24) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:246) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:241) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-hamster_server.jar:?]
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_291]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-hamster_server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_291]
[19:07:14] [Worker-Main-14/ERROR]: Parsing error loading recipe mechanicaltech:windsail_from_generic
com.google.gson.JsonSyntaxException: Unknown item tag 'c:wood_gears'
        at net.minecraft.class_1856.method_8107(class_1856.java:171) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1856.method_8102(class_1856.java:147) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869.method_8157(class_1869.java:225) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869.method_8159(class_1869.java:24) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:246) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:241) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-hamster_server.jar:?]
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_291]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-hamster_server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_291]
[19:07:14] [Worker-Main-14/ERROR]: Parsing error loading recipe mechanicaltech:spindle_from_generic
com.google.gson.JsonSyntaxException: Unknown item tag 'c:wood_gears'
        at net.minecraft.class_1856.method_8107(class_1856.java:171) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1856.method_8102(class_1856.java:147) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869.method_8157(class_1869.java:225) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869.method_8159(class_1869.java:24) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:246) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:241) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-hamster_server.jar:?]
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_291]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-hamster_server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_291]
[19:07:14] [Worker-Main-14/ERROR]: Parsing error loading recipe mechanicaltech:sawmill_from_generic
com.google.gson.JsonSyntaxException: Unknown item tag 'c:wood_gears'
        at net.minecraft.class_1856.method_8107(class_1856.java:171) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1856.method_8102(class_1856.java:147) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869.method_8157(class_1869.java:225) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869.method_8159(class_1869.java:24) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:246) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:241) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-hamster_server.jar:?]
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_291]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-hamster_server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_291]
[19:07:14] [Worker-Main-14/ERROR]: Parsing error loading recipe mechanicaltech:grinder_common
com.google.gson.JsonSyntaxException: Unknown item 'c:wood_gears'
        at net.minecraft.class_1856.method_17873(class_1856.java:165) ~[intermediary-hamster_server.jar:?]
        at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_291]
        at net.minecraft.class_1856.method_8107(class_1856.java:165) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1856.method_8102(class_1856.java:147) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869.method_8157(class_1869.java:225) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869.method_8159(class_1869.java:24) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:246) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:241) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-hamster_server.jar:?]
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_291]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-hamster_server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_291]
[19:07:14] [Worker-Main-14/ERROR]: Parsing error loading recipe mechanicaltech:waterwheel_from_generic
com.google.gson.JsonSyntaxException: Unknown item tag 'c:wood_gears'
        at net.minecraft.class_1856.method_8107(class_1856.java:171) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1856.method_8102(class_1856.java:147) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869.method_8157(class_1869.java:225) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869.method_8159(class_1869.java:24) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:246) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:241) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-hamster_server.jar:?]
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_291]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-hamster_server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-hamster_server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_291]

And after installing I have another mod named as "Mechanical Tech" which I wasn't installed. I dont want to install another mod and have some missing dependences with it. It is disgusting!

**Comment by Miros77** [comment]
Install Cotton Resources,

**Comment by Miros77** [comment]
c - id of the Cotton Resources

**Comment by Miros77** [comment]
Mechanical Tech this mod has a mill it is necessary for crafting flour and cocoa.
I can remove the Mechanical Tech mod. I will make a separate mod

**Comment by Miros77** [comment]
with the release of 1.3.0, this mod will be removed

**Comment by Miros77** [comment]
fixed in 1.3.0 [Realistic Bakery Products 1.3.0 [Fabric] 1.16.x](https://www.curseforge.com/minecraft/mc-mods/realistic-bakery-products-fabric/files/3758477)
